### ISSUE TITLE
Missing some focusable elements

### ISSUE THREAD

**Issue by stephenmathieson** [jkup/focusable#7]
`summary` elements are in the native tab order, as well as elements with a positive tab index.

Would you be up for merging a PR adding these?

**Comment by stephenmathieson** [comment]
Also, `output` elements.

**Comment by limonte** [comment]
`<summary>` is added in https://github.com/jkup/focusable/commit/f633f9890551c7cb3b6b2a21e5b00e4e3f1b0527

`<output>` shoutdn't be focusable (try https://developer.mozilla.org/en-US/docs/Web/HTML/Element/output)

Therefore this issue can be closed.

**Comment by stephenmathieson** [comment]
`<div tabindex="1">` is focusable but not included here. I disagree that the should be closed.

**Comment by limonte** [comment]
> `<div tabindex="1">` is focusable but not included here. I disagree that the should be closed.

Right, here's the PR: https://github.com/jkup/focusable/pull/9
