### ISSUE TITLE
Would you mind making a release on functional changed in index.js?

### ISSUE THREAD

**Issue by limonte** [jkup/focusable#8]
I'm watching releases of `focusable` to be notified on each change in the project.

Recently `<summary>` was added but there's no release after that, so I missed that feature.

Would it be okay for you @jkup to create a release after each significant change? It takes around 1 minute with GitHub UI to create a release.

**Comment by jkup** [comment]
Not at all! That's my bad. I've been neglecting the project. I'll look at your other PRs. and cut a release after merging them. Thanks for the ping!
